### ISSUE TITLE
Change casing of context.fhirbundle to context.fhirBundle?

### ISSUE THREAD

**Issue by jmandel** [ljoy913/shc-decoder#12]
https://github.com/smart-on-fhir/smart-health-card-decoder/blob/2b18d998c4fdd975b473906e3efc3bd992302315/src/context.ts#L21

I just tripped over this and wanted to get your take: is there a reason not to match the casing (`fhirBundle`) from the VC claim here in the context property?

**Comment by ljoy913** [comment]
Fixed by #13
