### ISSUE TITLE
Reconcile package name with repo name

### ISSUE THREAD

**Issue by jmandel** [ljoy913/shc-decoder#9]
I think it'd be good to rename the repo to `smart-health-card-decoder` or the package to `shc-decoder`. @ljoy913 does this make sense, and do you have a preference?

**Comment by ljoy913** [comment]
I does make sense; I prefer the longer 'smart-health-card-decoder' name.

**Comment by jmandel** [comment]
Done! GitHub should keep the old repository name working for links/git-configs that already exist.
